package com.liu.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import com.liu.entity.Converter1;
import com.liu.entity.TestConvert;

import com.liu.entity.Student;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "STUDENT".
*/
public class StudentDao extends AbstractDao<Student, Long> {

    public static final String TABLENAME = "STUDENT";

    /**
     * Properties of entity Student.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Age = new Property(1, String.class, "age", false, "AGE");
        public final static Property Te = new Property(2, String.class, "te", false, "info");
        public final static Property TestConvert = new Property(3, Integer.class, "testConvert", false, "TEST_CONVERT");
        public final static Property TeacherId = new Property(4, Long.class, "teacherId", false, "teacher_id");
    }

    private DaoSession daoSession;

    private final Converter1 testConvertConverter = new Converter1();
    private Query<Student> teacher_StudentsQuery;

    public StudentDao(DaoConfig config) {
        super(config);
    }
    
    public StudentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"STUDENT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"AGE\" TEXT NOT NULL ," + // 1: age
                "\"info\" TEXT," + // 2: te
                "\"TEST_CONVERT\" INTEGER," + // 3: testConvert
                "\"teacher_id\" INTEGER NOT NULL );"); // 4: teacherId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"STUDENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Student entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getAge());
 
        String te = entity.getTe();
        if (te != null) {
            stmt.bindString(3, te);
        }
 
        TestConvert testConvert = entity.getTestConvert();
        if (testConvert != null) {
            stmt.bindLong(4, testConvertConverter.convertToDatabaseValue(testConvert));
        }
        stmt.bindLong(5, entity.getTeacherId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Student entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getAge());
 
        String te = entity.getTe();
        if (te != null) {
            stmt.bindString(3, te);
        }
 
        TestConvert testConvert = entity.getTestConvert();
        if (testConvert != null) {
            stmt.bindLong(4, testConvertConverter.convertToDatabaseValue(testConvert));
        }
        stmt.bindLong(5, entity.getTeacherId());
    }

    @Override
    protected final void attachEntity(Student entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Student readEntity(Cursor cursor, int offset) {
        Student entity = new Student( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // age
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // te
            cursor.isNull(offset + 3) ? null : testConvertConverter.convertToEntityProperty(cursor.getInt(offset + 3)), // testConvert
            cursor.getLong(offset + 4) // teacherId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Student entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setAge(cursor.getString(offset + 1));
        entity.setTe(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTestConvert(cursor.isNull(offset + 3) ? null : testConvertConverter.convertToEntityProperty(cursor.getInt(offset + 3)));
        entity.setTeacherId(cursor.getLong(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Student entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Student entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Student entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "students" to-many relationship of Teacher. */
    public List<Student> _queryTeacher_Students(Long teacherId) {
        synchronized (this) {
            if (teacher_StudentsQuery == null) {
                QueryBuilder<Student> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.TeacherId.eq(null));
                teacher_StudentsQuery = queryBuilder.build();
            }
        }
        Query<Student> query = teacher_StudentsQuery.forCurrentThread();
        query.setParameter(0, teacherId);
        return query.list();
    }

}
